# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-18 21:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospedagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_checkin', models.DateTimeField(auto_now_add=True, verbose_name='Data checkin')),
                ('data_checkout', models.DateTimeField(auto_now=True, null=True, verbose_name='Data checkout')),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('fechada', 'Fechada')], default='aberta', max_length=255, verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='Hospede',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('telefone', models.IntegerField(verbose_name='Telefone')),
                ('email', models.CharField(max_length=255, verbose_name='Email')),
                ('cpf', models.IntegerField(verbose_name='CPF')),
                ('endereco', models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereco')),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=255, verbose_name='Razao social')),
                ('telefone', models.IntegerField(verbose_name='Telefone')),
                ('valor_diaria', models.FloatField(verbose_name='Valor diaria')),
                ('endereco', models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereco')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hotel', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='hospede',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clientes_hotel', to='comum.Hotel'),
        ),
        migrations.AddField(
            model_name='hospedagem',
            name='hospede',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comum.Hospede'),
        ),
        migrations.AddField(
            model_name='hospedagem',
            name='hotel',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comum.Hotel'),
        ),
    ]
