# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-23 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0002_auto_20180219_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospedagem',
            name='valor_debito',
            field=models.FloatField(blank=True, null=True, verbose_name='Valor debito'),
        ),
        migrations.AlterField(
            model_name='hospedagem',
            name='data_checkout',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data checkout'),
        ),
    ]
