# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-23 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0004_remove_hospedagem_valor_debito'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospedagem',
            name='valor_debito',
            field=models.FloatField(blank=True, null=True, verbose_name='Valor debito'),
        ),
    ]
