# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-24 22:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0005_hospedagem_valor_debito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hoteis', to=settings.AUTH_USER_MODEL),
        ),
    ]
